---
title: "Week 9"
subtitle: "SEM"
da  te: 2023-04-10
---
## Before Class

### Articles

{{< fa book >}} McCoach, D. B., & Cintron, D. (2022). Introduction to Modern Modelling Methods (1st edition). SAGE Publications Ltd.

[Chapters 4 and 5](/readings/sem.pdf)

  - Describe how to enact the tracing rule used to calculate the magnitude of a particular indirect effect.

  - What is the purpose of SEM and how does it differ from other types of statistical models?

  - What are the key components of an SEM model, including latent variables, observed variables, and paths between variables?

  - How do you specify an SEM model, including selecting the appropriate measurement model and structural model?

  - How do you evaluate the fit of an SEM model and what are some common fit indices used in SEM?

  - How do you interpret the results of an SEM analysis, including the path coefficients and factor loadings?

  - What are some common assumptions of SEM and how can you assess whether these assumptions are met?

  - How do you handle missing data in SEM and what are the implications of missing data for SEM analysis?

  - What are some common challenges and limitations of SEM and how can they be addressed?

  - What are the best practices for reporting SEM results and how can you communicate your findings effectively?
  
  - Come up with a hypothetical path model. Represent it both pictorially and as a series of equations.

