---
title: "Schedule"
sidebar: false
toc: false
page-layout: full
---

```{r packages-data, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

::: schedule-page
Here's your roadmap for the semester!

<ul class="icon-list">

<li><i class="fas fa-book-reader"></i> Readings should be completed ***before*** each class session</li>

<li><i class="fas fa-tv"></i> Slides and other class materials will be added on the day of class</li>

<li><i class="fas fa pen-ruler"></i> Assignments are due at noon on the day they are due (unless otherwise stated)</li>

</ul>
| Week  | Date         | Topic                                           | Content                                                   | Class                           | Labs                          |
|-------|--------------|-------------------------------------------------|-----------------------------------------------------------|---------------------------------|-------------------------------|
|       |              |                                                 |                                                           |                                 |                               |
| 1     | 1/30/23      | Introduction                                    |                                                           |                                 |                               |
|       | 2/1/23       | Cleaning   data                                 | [{{<    fa   book-open-reader >}}](/schedule/01-week.qmd) |        {{<   fa laptop-code >}} |                               |
| 2     | 2/6/23       | Robust methods:   bootstrapping and permutation | [{{<    fa   book-open-reader >}}](/schedule/02-week.qmd) |        {{<   fa laptop-code >}} |                               |
|       | 2/8/23       | Lab 1                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 3     | 2/13/23      | Missing data                                    | [{{<    fa   book-open-reader >}}](/schedule/03-week.qmd) |        {{<   fa laptop-code >}} |                               |
|       | 2/15/23      | Lab 2                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 4     | 2/20/23      | Ordinal   Regression                            | [{{<    fa   book-open-reader >}}](/schedule/04-week.qmd) |        {{<   fa laptop-code >}} |                               |
|       | 2/22/23      | Lab 3                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 5     | 2/27/23      | Poisson   regression                            | [{{<    fa   book-open-reader >}}](/schedule/04-week.qmd) |        {{<   fa laptop-code >}} |                               |
|       | 3/1/23       | Lab 3                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 6     | 3/6/23       | Bayesian   analysis                             | [{{<    fa   book-open-reader >}}](/schedule/05-week.qmd) |        {{<   fa laptop-code >}} |                               |
|       | 3/8/23       | Lab 4                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 7     | Spring Break |                                                 |                                                           |                                 |                               |
| 8     | 3/20/23      | Mediation                                       | [{{<    fa   book-open-reader >}}](/schedule/06-week.qmd) |        {{<   fa laptop-code >}} |                               |
|       | 3/22/23      | Lab 5                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 9     | 3/27/23      | Path   modeling/SEM                             |                                                           |                                 |                               |
|       | 3/29/23      | Lab 6                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 10    | 4/3/23       | PCA                                             |                                                           |        {{<   fa laptop-code >}} |                               |
|       | 4/5/23       | Lab 7                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 11    | 4/10/23      | Clustering:   K-means/hierarichal clustering    |                                                           |        {{<   fa laptop-code >}} |                               |
|       | 4/12/23      | Lab 8                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 12    | 4/17/23      | Multilevel   modeling                           |                                                           |        {{<   fa laptop-code >}} |                               |
|       | 4/19/23      | Lab 9                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 13    | 4/24/23      | Growth curve   modeling (GCA)                   |                                                           |        {{<   fa laptop-code >}} |                               |
|       | 4/26/23      | Lab 9                                           |                                                           |                                 |        {{<   fa pen-ruler >}} |
| 14    | Reading Week |                                                 |                                                           |                                 |                               |
| 15    | Finals       |                                                 |                                                           |                                 |                               |
|       |              |                                                 |                                                           |                                 |                               |
:::
